/// Generated pin table
/// This file is generated by build.rs
/// Do not edit this file directly
///
#[macro_export]
macro_rules! foreach_pin {
    (P0_0:ident, PORT0:ident, 0:expr, 0:expr) => {
                impl Pin for peripherals::P0_0 {
                    fn pin_port(&self) -> u8 {
                        0 * 16 + 0
                    }
                }
            };
}
