use std::fs::File;
use std::io::Write;

fn main() {
    let mut file = File::create("src/generated.rs").unwrap();

    let pins_table = vec![
        // Add RA4M1-specific pin definitions here
        ("P0_0", "PORT0", 0, 0),
    ];

    make_table(&mut file, "foreach_pin", &pins_table);

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/generated.rs");
}

fn make_table(out: &mut File, name: &str, data: &Vec<(&str, &str, u8, u8)>) {
    writeln!(out, "/// Generated pin table").unwrap();
    writeln!(out, "/// This file is generated by build.rs").unwrap();
    writeln!(out, "/// Do not edit this file directly").unwrap();
    writeln!(out, "///").unwrap();
    writeln!(out, "#[macro_export]").unwrap();
    writeln!(out, "macro_rules! {} {{", name).unwrap();
    for (pin_name, port_name, port_num, pin_num) in data {
        writeln!(
            out,
            "    ({}:ident, {}:ident, {}:expr, {}:expr) => {{\n                impl Pin for peripherals::{} {{\n                    fn pin_port(&self) -> u8 {{\n                        {} * 16 + {}\n                    }}\n                }}\n            }};",
            pin_name, port_name, port_num, pin_num, pin_name, port_num, pin_num
        )
        .unwrap();
    }
    writeln!(out, "}}").unwrap();
}